---
    name: CI
    
    on: # yamllint disable-line rule:truthy
      push:
        branches: [main]
      pull_request:
        branches: [main]
    
    concurrency:
      group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
      cancel-in-progress: true

    jobs:
        lint-test:
            name: Lint and Test
            runs-on: ubuntu-22.04
            strategy:
              matrix:
                python-version: ["3.12"]

            steps:
                - uses: actions/checkout@v4
                - name: Set up Python
                  uses: actions/setup-python@v5
                  with:
                    python-version: ${{ matrix.python-version }}

                - name: Install pipx
                  run: python -m pip install --upgrade pipx

                - name: Install UV
                  run: pipx install uv

                - name: Display Python version
                  run: uv run python -c "import sys; print(sys.version)"

                - name: Install dependencies
                  run: uv lock; uv sync --extra=dev; uv build

                # - name: Lint Python
                #   run: make check-python-nofix

                - name: Test Python
                  run: uv run pytest --cov

                # - name: Cleanup residue file
                #   run: make clean
    
    